/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/admin/login": {
    /** Authenticate as a platform admin and receive a JWT. */
    post: {
      parameters: {
        body: {
          /** Admin credentials */
          body: definitions["handlers.loginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["adminauth.AuthResult"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects": {
    /** List all projects accessible by the authenticated admin. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["adminauth.ProjectWithRole"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Create a new project as a platform admin. */
    post: {
      parameters: {
        body: {
          /** Project name */
          body: definitions["handlers.createProjectRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["adminauth.Project"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/admin-roles": {
    /** List all admin roles assigned to a project. super_admin only. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["adminauth.AdminProjectRole"][];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Assign an admin user to a project with a specific role. super_admin only. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        body: {
          /** Admin user ID and role */
          body: definitions["handlers.assignRoleRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/admin-roles/{aid}": {
    /** Remove an admin user's access to a project. super_admin only. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Admin user ID */
          aid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/audit-logs": {
    /** List all audit log entries for a project with cursor-based pagination. Admin only. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        query: {
          /** Pagination cursor (created_at timestamp) */
          cursor?: string;
          /** Max results (1-100) */
          limit?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/collections": {
    /** List all collections for a project. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["collections.Collection"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Create a new dynamic collection with a schema. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        body: {
          /** Collection definition */
          body: definitions["handlers.createCollectionRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["collections.Collection"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/collections/{cid}": {
    /** Get a collection definition by ID. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Collection ID */
          cid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["collections.Collection"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Update the schema of an existing collection. */
    put: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Collection ID */
          cid: string;
        };
        body: {
          /** Updated schema */
          body: definitions["handlers.updateCollectionSchemaRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["collections.Collection"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Delete a collection and all its records. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Collection ID */
          cid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/roles": {
    /** List all RBAC roles for a project. super_admin only. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rbac.RoleWithPermissions"][];
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Create a new RBAC role for a project. super_admin only. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        body: {
          /** Role name */
          body: definitions["handlers.createRoleRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["rbac.Role"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/roles/{rid}": {
    /** Delete a role and its permissions. super_admin only. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Role ID */
          rid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/roles/{rid}/permissions": {
    /** List all permissions assigned to a role. super_admin only. */
    get: {
      parameters: {
        path: {
          /** Role ID */
          rid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rbac.Permission"][];
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Add a (resource, action) permission to a role. super_admin only. */
    post: {
      parameters: {
        path: {
          /** Role ID */
          rid: string;
        };
        body: {
          /** Resource and action */
          body: definitions["handlers.permissionRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["rbac.Permission"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Remove a (resource, action) permission from a role. super_admin only. */
    delete: {
      parameters: {
        path: {
          /** Role ID */
          rid: string;
        };
        body: {
          /** Resource and action */
          body: definitions["handlers.permissionRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/projects/{pid}/users/{uid}/role": {
    /** Get the RBAC role assigned to a SaaS user for a project. super_admin only. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** User ID */
          uid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rbac.UserProjectRole"];
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Assign an RBAC role to a SaaS user for a project. super_admin only. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** User ID */
          uid: string;
        };
        body: {
          /** Role ID */
          body: definitions["handlers.userRoleRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rbac.UserProjectRole"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Remove the RBAC role assignment from a SaaS user. super_admin only. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** User ID */
          uid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
        /** Forbidden */
        403: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/admin/setup": {
    /** Create the first super_admin and default project. Only works once. */
    post: {
      parameters: {
        body: {
          /** Admin credentials */
          body: definitions["handlers.setupRequest"];
        };
      };
      responses: {
        /** token, admin, project */
        201: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Conflict */
        409: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/auth/login": {
    /** Authenticate and receive a JWT token for API access. */
    post: {
      parameters: {
        body: {
          /** Login credentials */
          body: definitions["handlers.authRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["auth.AuthResult"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/auth/signup": {
    /** Create a new end-user account scoped to a project. */
    post: {
      parameters: {
        body: {
          /** Signup credentials */
          body: definitions["handlers.authRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["auth.AuthResult"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Conflict */
        409: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants": {
    /** List all tenants within a project. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tenant.Tenant"][];
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Create a new tenant within a project. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        body: {
          /** Tenant name */
          body: definitions["handlers.createTenantRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["tenant.Tenant"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}": {
    /** Get tenant details by ID. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tenant.Tenant"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Delete a tenant and its data. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/collections/{cid}/records": {
    /** List records in a collection with cursor-based pagination. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** Collection ID */
          cid: string;
        };
        query: {
          /** Pagination cursor (record ID) */
          cursor?: string;
          /** Page size (default 50, max 100) */
          limit?: number;
        };
      };
      responses: {
        /** data: [Record], next_cursor: string */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Create a new record in a collection. Data is validated against the collection schema. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** Collection ID */
          cid: string;
        };
        body: {
          /** Record data */
          body: definitions["handlers.createRecordRequest"];
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["records.Record"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/collections/{cid}/records/{rid}": {
    /** Get a single record by ID. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** Collection ID */
          cid: string;
          /** Record ID */
          rid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["records.Record"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Replace a record's data (full JSONB replacement). Validated against the schema. */
    put: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** Collection ID */
          cid: string;
          /** Record ID */
          rid: string;
        };
        body: {
          /** Updated data */
          body: definitions["handlers.updateRecordRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["records.Record"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Delete a record by ID. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** Collection ID */
          cid: string;
          /** Record ID */
          rid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/files": {
    /** List all files for a tenant with cursor-based pagination. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
        };
        query: {
          /** Pagination cursor */
          cursor?: string;
          /** Max results (1-100) */
          limit?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Upload a file to S3-compatible storage and store metadata. Tenant-scoped. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
        };
        formData: {
          /** File to upload */
          file: unknown;
        };
      };
      responses: {
        /** Created */
        201: {
          schema: definitions["handlers.fileResponse"];
        };
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/files/{fid}": {
    /** Get file metadata and a presigned download URL. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** File ID */
          fid: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["handlers.fileResponse"];
        };
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
    /** Delete a file from S3 storage and remove its metadata. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** File ID */
          fid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Not Found */
        404: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/users": {
    /** Assign an existing user to a tenant. */
    post: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
        };
        body: {
          /** User ID */
          body: definitions["handlers.assignUserRequest"];
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/tenants/{tid}/users/{uid}": {
    /** Remove a user's access to a tenant. */
    delete: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
          /** Tenant ID */
          tid: string;
          /** User ID */
          uid: string;
        };
      };
      responses: {
        /** No Content */
        204: never;
        /** Bad Request */
        400: {
          schema: { [key: string]: string };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/api/projects/{pid}/ws": {
    /** Upgrade to WebSocket for realtime events. Authenticate via ?token= query param. Requires Bearer JWT. */
    get: {
      parameters: {
        path: {
          /** Project ID */
          pid: string;
        };
        query: {
          /** JWT token */
          token: string;
        };
      };
      responses: {
        /** Switching Protocols */
        101: unknown;
        /** Unauthorized */
        401: {
          schema: { [key: string]: string };
        };
      };
    };
  };
  "/health": {
    /** Returns the health status of the server. */
    get: {
      responses: {
        /** status: ok */
        200: {
          schema: { [key: string]: string };
        };
      };
    };
  };
}

export interface definitions {
  "adminauth.AdminProjectRole": {
    admin_user_id?: string;
    created_at?: string;
    email?: string;
    project_id?: string;
    role?: string;
  };
  "adminauth.AdminUser": {
    created_at?: string;
    email?: string;
    id?: string;
    role?: string;
  };
  "adminauth.AuthResult": {
    admin?: definitions["adminauth.AdminUser"];
    token?: string;
  };
  "adminauth.Project": {
    admin_owner_id?: string;
    created_at?: string;
    id?: string;
    jwt_expiry?: number;
    name?: string;
  };
  "adminauth.ProjectWithRole": {
    admin_owner_id?: string;
    created_at?: string;
    id?: string;
    jwt_expiry?: number;
    name?: string;
    role?: string;
  };
  "auth.AuthResult": {
    token?: string;
    user?: definitions["auth.UserDTO"];
  };
  "auth.UserDTO": {
    email?: string;
    id?: string;
    project_id?: string;
  };
  "collections.Collection": {
    created_at?: string;
    id?: string;
    name?: string;
    project_id?: string;
    schema?: definitions["collections.Schema"];
  };
  "collections.Field": {
    name?: string;
    required?: boolean;
    type?: string;
  };
  "collections.Schema": {
    fields?: definitions["collections.Field"][];
  };
  "handlers.assignRoleRequest": {
    admin_user_id?: string;
    role?: string;
  };
  "handlers.assignUserRequest": {
    user_id?: string;
  };
  "handlers.authRequest": {
    email?: string;
    password?: string;
    project_id?: string;
  };
  "handlers.createCollectionRequest": {
    name?: string;
    schema?: definitions["collections.Schema"];
  };
  "handlers.createProjectRequest": {
    name?: string;
  };
  "handlers.createRecordRequest": {
    data?: { [key: string]: unknown };
  };
  "handlers.createRoleRequest": {
    name?: string;
  };
  "handlers.createTenantRequest": {
    name?: string;
  };
  "handlers.fileResponse": {
    created_at?: string;
    filename?: string;
    id?: string;
    mime_type?: string;
    presigned_url?: string;
    project_id?: string;
    size?: number;
    tenant_id?: string;
    uploaded_by?: string;
  };
  "handlers.loginRequest": {
    email?: string;
    password?: string;
  };
  "handlers.permissionRequest": {
    action?: string;
    resource?: string;
  };
  "handlers.setupRequest": {
    email?: string;
    password?: string;
  };
  "handlers.updateCollectionSchemaRequest": {
    schema?: definitions["collections.Schema"];
  };
  "handlers.updateRecordRequest": {
    data?: { [key: string]: unknown };
  };
  "handlers.userRoleRequest": {
    role_id?: string;
  };
  "rbac.Permission": {
    action?: string;
    id?: string;
    resource?: string;
    role_id?: string;
  };
  "rbac.Role": {
    created_at?: string;
    id?: string;
    name?: string;
    project_id?: string;
  };
  "rbac.RoleWithPermissions": {
    created_at?: string;
    id?: string;
    name?: string;
    permissions?: definitions["rbac.Permission"][];
    project_id?: string;
  };
  "rbac.UserProjectRole": {
    created_at?: string;
    project_id?: string;
    role_id?: string;
    role_name?: string;
    user_id?: string;
  };
  "records.Record": {
    collection_id?: string;
    created_at?: string;
    data?: { [key: string]: unknown };
    id?: string;
    project_id?: string;
    tenant_id?: string;
    updated_at?: string;
  };
  "tenant.Tenant": {
    created_at?: string;
    id?: string;
    name?: string;
    project_id?: string;
  };
}

export interface operations {}

export interface external {}
